/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cgc;


import org.junit.Test;

import static junit.framework.TestCase.assertTrue;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
